"""
AI 이미지 메타데이터/출처 검사 모듈.

메타데이터 신호는 **결정적 신호(decisive)**와 **약한 흔적(weak)**으로 구분한다.
  - 결정적 신호: AI 생성 도구의 명확한 파라미터 구조나 도구명이 포함된 경우.
  - 약한 흔적: C2PA/JUMBF 박스 단순 존재 등 출처는 있으나 AI 단정 불가.
  - has_ai_signal은 결정적 신호가 있을 때만 True.

Python 3.10+ 환경에서 `pip install c2pa-python` 시 C2PA 정식 매니페스트 검증이
자동으로 활성화된다. 미설치 상태가 정상이며 에러를 내지 않는다.
"""

import json as _json
import re
import os
from typing import Dict, List, Any, Optional, Tuple

# 파일 크기 상한: 이 이상이면 raw 바이트 스캔 건너뜀
MAX_METADATA_SCAN_BYTES = 50 * 1024 * 1024  # 50MB

# ── PNG text chunk 키 전략 ────────────────────────────────────────────────
# 키 존재만으로 신호 삼지 않고, 값 내부 패턴 검사만 수행.
# "parameters"/"prompt"/"dream" → SD 파라미터 구조 검사
# "workflow"                   → ComfyUI 노드 그래프 JSON 구조 검사
# "comment"/"description"      → 값에 명시적 AI 도구명이 있을 때만 신호

# SD 파라미터 구조를 나타내는 정규식
# A1111 webui: "Steps: 20, Sampler: Euler a, CFG scale: 7"
# A1111 Dream: "cfg=7.5, steps=30" (등호 형식)
_SD_PARAM_PATTERN = re.compile(
    r"(?:steps\s*[:=]\s*\d|sampler\s*:|cfg\s*(?:scale)?\s*[:=]\s*\d|model\s+hash\s*:|seed\s*[:=]\s*\d)",
    re.IGNORECASE,
)

# ComfyUI 노드 그래프 JSON 검사용 키
_COMFYUI_JSON_KEYS = {"class_type", "nodes"}

# EXIF/PNG Software 태그에서 탐지할 AI 도구명 패턴 (소문자 기준, 풀네임 매칭)
# "diffusion" 단독은 제외 — 카메라 앱 등 오탐 방지
_AI_SOFTWARE_PATTERNS_DECISIVE = [
    "stable diffusion",
    "dall-e",
    "dall·e",
    "midjourney",
    "adobe firefly",
    "bing image creator",
    "comfyui",
    "automatic1111",
    "novelai",
    "invokeai",
    "leonardo ai",
    "nightcafe",
]

# raw bytes 도구명 검색용 (bytes 형태, 풀네임)
_AI_TOOL_BYTES_DECISIVE = [
    b"stable diffusion",
    b"dall-e",
    b"dall\xc2\xb7e",   # DALL·E UTF-8
    b"midjourney",
    b"adobe firefly",
    b"bing image creator",
    b"comfyui",
    b"automatic1111",
    b"novelai",
    b"invokeai",
]

# XMP raw 바이트에서 탐지할 마커 패턴 (소문자 bytes)
# trainedAlgorithmicMedia, Generated by AI 등 명시적 마커만 결정적 신호로 처리
_XMP_DECISIVE_PATTERNS = [
    b"trainedalgorithmicmedia",
    b"compositewithtrainedalgorithmicmedia",
    b"aigenerated",
    b"generated by ai",
]
# 약한 흔적 패턴 (C2PA 존재 자체)
_XMP_WEAK_PATTERNS = [
    b"c2pa",
    b"contentauth",
    b"content credentials",
    b"digitalsourcetype",
]

# C2PA/JUMBF 시그니처 (raw bytes) — 약한 흔적
_C2PA_SIGNATURES = [
    b"c2pa",
    b"jumb",
    b"urn:uuid:",
]

# JPEG APP11 마커 (C2PA는 APP11에 들어감) — 약한 흔적
_JPEG_APP11_MARKER = b"\xff\xeb"


def _check_sd_params(value: str) -> bool:
    """값 내부에 SD 파라미터 구조(Steps:, Sampler:, CFG scale: 등)가 있는지 확인."""
    matches = _SD_PARAM_PATTERN.findall(value)
    # 2개 이상의 SD 파라미터 키워드가 있어야 구조적 신호로 인정
    return len(matches) >= 2


def _check_comfyui_json(value: str) -> bool:
    """값이 ComfyUI 노드 그래프 JSON 구조인지 확인."""
    value_stripped = value.strip()
    if not value_stripped.startswith("{"):
        return False
    try:
        obj = _json.loads(value_stripped)
        if not isinstance(obj, dict):
            return False
        return bool(_COMFYUI_JSON_KEYS & set(obj.keys()))
    except Exception:
        return False


def _check_explicit_ai_tool_in_value(value: str) -> Optional[str]:
    """값 내부에 명시적 AI 도구명이 있는지 확인."""
    val_lower = value.lower()
    for pattern in _AI_SOFTWARE_PATTERNS_DECISIVE:
        if pattern in val_lower:
            return pattern
    return None


def _check_png_text(img_info: Dict[str, Any]) -> Tuple[List[str], bool]:
    """
    PNG text chunk / info dict에서 AI 신호를 탐지한다.
    Returns: (signals, any_decisive)
    """
    decisive_signals: List[str] = []
    weak_signals: List[str] = []

    for key, value in img_info.items():
        key_lower = str(key).lower()
        value_str = str(value) if value else ""

        if key_lower in ("parameters", "prompt", "dream"):
            # SD 파라미터 구조 검사
            if _check_sd_params(value_str):
                decisive_signals.append(
                    f"PNG text chunk '{key}': Stable Diffusion parameters structure detected"
                )
            elif _check_explicit_ai_tool_in_value(value_str):
                tool = _check_explicit_ai_tool_in_value(value_str)
                decisive_signals.append(
                    f"PNG text chunk '{key}': AI tool name '{tool}' found"
                )

        elif key_lower == "workflow":
            # ComfyUI JSON 구조 검사
            if _check_comfyui_json(value_str):
                decisive_signals.append(
                    f"PNG text chunk 'workflow': ComfyUI node graph JSON detected"
                )
            elif _check_explicit_ai_tool_in_value(value_str):
                tool = _check_explicit_ai_tool_in_value(value_str)
                decisive_signals.append(
                    f"PNG text chunk 'workflow': AI tool name '{tool}' found"
                )

        elif key_lower in ("comment", "description", "software"):
            # 키 존재만으로 신호 삼지 않고 값 내부에 AI 도구명이 명시될 때만 신호
            tool = _check_explicit_ai_tool_in_value(value_str)
            if tool:
                decisive_signals.append(
                    f"PNG text chunk '{key}': AI tool name '{tool}' found"
                )

        # 그 외 키에서도 SD 파라미터 구조나 명시적 AI 도구명 검사
        elif value_str:
            if _check_sd_params(value_str):
                decisive_signals.append(
                    f"PNG text chunk '{key}': Stable Diffusion parameters structure detected"
                )
            else:
                tool = _check_explicit_ai_tool_in_value(value_str)
                if tool:
                    decisive_signals.append(
                        f"PNG text chunk '{key}': AI tool name '{tool}' found"
                    )

    all_signals = decisive_signals + weak_signals
    return all_signals, len(decisive_signals) > 0


def _check_software_string(software: str) -> Optional[Tuple[str, bool]]:
    """
    Software 문자열에서 AI 도구명을 탐지한다.
    Returns: (signal_message, is_decisive) 또는 None
    """
    sw_lower = software.lower()
    for pattern in _AI_SOFTWARE_PATTERNS_DECISIVE:
        if pattern in sw_lower:
            return (f"Software tag contains AI tool: '{software}'", True)
    return None


def _check_exif(img) -> Tuple[List[str], bool]:
    """
    Pillow로 읽은 EXIF에서 AI 신호를 탐지한다.
    Returns: (signals, any_decisive)
    """
    signals: List[str] = []
    decisive = False
    try:
        exif_data = img._getexif()
        if exif_data is None:
            return signals, decisive
        # EXIF 태그 번호: 0x0131=Software(305), 0x010F=Make(271), 0x0110=Model(272), 0x000B=ProcessingSoftware(11)
        target_tags = {305, 271, 272, 11}
        for tag_id, value in exif_data.items():
            if tag_id in target_tags and isinstance(value, (str, bytes)):
                sw = value.decode("utf-8", errors="replace") if isinstance(value, bytes) else value
                result = _check_software_string(sw)
                if result:
                    msg, is_dec = result
                    signals.append(msg)
                    if is_dec:
                        decisive = True
    except Exception:
        pass
    return signals, decisive


def _check_xmp_bytes(raw_lower: bytes) -> Tuple[List[str], bool]:
    """
    파일 raw bytes(소문자)에서 XMP 패킷 및 AI 마커를 탐지한다.
    Returns: (signals, any_decisive)
    """
    decisive_signals: List[str] = []
    weak_signals: List[str] = []

    for pattern in _XMP_DECISIVE_PATTERNS:
        if pattern in raw_lower:
            decisive_signals.append(
                f"XMP marker found (decisive): '{pattern.decode('utf-8', errors='replace')}'"
            )

    for pattern in _XMP_WEAK_PATTERNS:
        if pattern in raw_lower:
            weak_signals.append(
                f"XMP/raw marker found (weak): '{pattern.decode('utf-8', errors='replace')}'"
            )

    return decisive_signals + weak_signals, len(decisive_signals) > 0


def _check_c2pa_signatures(raw_bytes: bytes, raw_lower: bytes) -> Tuple[List[str], bool]:
    """
    파일 raw bytes에서 C2PA/JUMBF 시그니처 및 JPEG APP11 마커를 탐지한다.
    C2PA 단순 존재는 약한 흔적. c2pa-python으로 AI assertion 확인 시 결정적.
    Returns: (signals, any_decisive)
    """
    signals: List[str] = []
    for sig in _C2PA_SIGNATURES:
        if sig in raw_lower:
            signals.append(
                f"C2PA/JUMBF signature found (weak): '{sig.decode('utf-8', errors='replace')}'"
            )
            break
    if _JPEG_APP11_MARKER in raw_bytes:
        signals.append("JPEG APP11 marker found (weak, possible C2PA manifest)")
    return signals, False  # 단순 존재는 약한 흔적 — decisive=False


def _check_ai_tool_in_raw_bytes(raw_lower: bytes) -> Tuple[List[str], bool]:
    """
    raw bytes(소문자)에서 AI 도구명 풀네임을 직접 탐지한다.
    풀네임 매칭만 수행 (diffusion 단독 제외).
    Returns: (signals, any_decisive)
    """
    signals: List[str] = []
    for pattern_bytes in _AI_TOOL_BYTES_DECISIVE:
        if pattern_bytes in raw_lower:
            name = pattern_bytes.decode("utf-8", errors="replace")
            signals.append(f"AI tool name found in raw bytes (decisive): '{name}'")
    return signals, len(signals) > 0


def _try_c2pa_optional(image_path: str, signals: List[str]) -> Tuple[Optional[str], bool]:
    """
    c2pa-python이 설치된 환경(Python 3.10+)에서만 정식 C2PA 매니페스트를 검증한다.
    AI assertion이 있으면 결정적 신호. 없으면 약한 흔적.
    Returns: (source, is_decisive)
    """
    try:
        import c2pa  # type: ignore  # noqa: F401
        try:
            reader = c2pa.Reader.from_file(image_path)
            manifest_store = reader.get_active_manifest()
            if manifest_store:
                for assertion in manifest_store.get("assertions", []):
                    label = str(assertion.get("label", "")).lower()
                    data = str(assertion.get("data", "")).lower()
                    if "ai" in label or "trainedalgorithmic" in data or "generated" in data:
                        signals.append(f"C2PA assertion (decisive): {assertion.get('label', 'unknown')}")
                        return "c2pa", True
                return "c2pa", False  # 매니페스트 있지만 AI assertion 없음 → 약한 흔적
        except Exception:
            pass
    except ImportError:
        pass
    return None, False


def inspect_metadata(image_path: str) -> Dict[str, Any]:
    """
    이미지 메타데이터/출처를 검사해 AI 생성 신호를 탐지한다.

    Args:
        image_path: 검사할 이미지 파일 경로

    Returns:
        {
            "has_ai_signal": bool,     # 결정적 신호 존재 여부 (하위호환)
            "decisive": bool,          # 결정적 신호 여부 (신규)
            "signals": [str, ...],     # 발견된 근거 문자열 목록 (결정적+약한 모두 포함)
            "source": "c2pa"|"metadata"|None,
            "checked": bool,
        }

    참고:
        - has_ai_signal은 결정적 신호가 있을 때만 True. 약한 흔적만 있으면 False.
        - 신호가 없어도 Real을 보장하지 않음 (SNS 등에서 메타데이터 제거됨).
        - 예외를 던지지 않고 checked=False로 graceful 반환.
    """
    empty_result: Dict[str, Any] = {
        "has_ai_signal": False,
        "decisive": False,
        "signals": [],
        "source": None,
        "checked": False,
    }

    if not image_path or not os.path.isfile(image_path):
        return empty_result

    try:
        from PIL import Image, UnidentifiedImageError

        # 파일 크기 확인 → 50MB 초과 시 raw 바이트 스캔 생략
        try:
            file_size = os.path.getsize(image_path)
        except Exception:
            file_size = 0

        skip_raw_scan = file_size > MAX_METADATA_SCAN_BYTES

        # raw bytes 읽기 (크기 제한 미초과 시에만)
        raw_bytes: Optional[bytes] = None
        raw_lower: Optional[bytes] = None
        if not skip_raw_scan:
            try:
                with open(image_path, "rb") as f:
                    raw_bytes = f.read()
                raw_lower = raw_bytes.lower()
            except Exception:
                pass

        signals: List[str] = []
        any_decisive = False
        source: Optional[str] = None

        # Pillow로 이미지 파싱 시도
        pillow_ok = False
        pillow_img = None
        try:
            pillow_img = Image.open(image_path)
            pillow_img.load()
            pillow_ok = True
        except Exception:
            pillow_ok = False

        if not pillow_ok:
            return empty_result

        # 1. Pillow 기반 탐지 (PNG text chunks, EXIF)
        try:
            png_sigs, png_dec = _check_png_text(pillow_img.info)
            signals.extend(png_sigs)
            if png_dec:
                any_decisive = True

            exif_sigs, exif_dec = _check_exif(pillow_img)
            signals.extend(exif_sigs)
            if exif_dec:
                any_decisive = True

            pillow_img.close()
        except Exception:
            pass

        # raw bytes 기반 탐지 (크기 제한 미초과 시에만)
        if raw_bytes is not None and raw_lower is not None:
            # 2. C2PA raw 시그니처 탐지 (약한 흔적)
            c2pa_raw_sigs, c2pa_raw_dec = _check_c2pa_signatures(raw_bytes, raw_lower)
            signals.extend(c2pa_raw_sigs)
            if c2pa_raw_dec:
                any_decisive = True

            # 3. XMP raw 패킷 탐지
            xmp_sigs, xmp_dec = _check_xmp_bytes(raw_lower)
            signals.extend(xmp_sigs)
            if xmp_dec:
                any_decisive = True

            # 4. AI 도구명 raw bytes 탐지 (풀네임 매칭, EXIF 파싱 실패 대비 폴백)
            raw_tool_sigs, raw_tool_dec = _check_ai_tool_in_raw_bytes(raw_lower)
            signals.extend(raw_tool_sigs)
            if raw_tool_dec:
                any_decisive = True
        elif skip_raw_scan:
            signals.append("raw byte scan skipped (file too large)")

        # 5. optional: c2pa-python 정식 검증 (Python 3.10+ 환경)
        c2pa_source, c2pa_dec = _try_c2pa_optional(image_path, signals)
        if c2pa_dec:
            any_decisive = True

        # 중복 신호 제거
        signals = list(dict.fromkeys(signals))

        # has_ai_signal은 결정적 신호가 있을 때만 True
        has_signal = any_decisive
        if len(signals) > 0:
            source = c2pa_source if c2pa_source else "metadata"

        return {
            "has_ai_signal": has_signal,
            "decisive": any_decisive,
            "signals": signals,
            "source": source,
            "checked": True,
        }

    except Exception:
        return empty_result
